POST http://localhost/kk-mgr/index.html
Accept: */*
Cache-Control: no-cache
Content-Type: application/json;charset=utf-8
Authorization:  {{auth_token}}

###

POST http://localhost/kk-mgr/register
Accept: */*
Cache-Control: no-cache
Content-Type: application/json;charset=utf-8

// {"username":"kinkim","password":"123456"}
{"username":"admin","password":"111111"}


###

POST http://localhost/kk-mgr/authenticate
Accept: */*
Cache-Control: no-cache
Content-Type: application/json;charset=utf-8

{"username":"kinkim","password":"123456"}
> {% client.global.set("auth_token", response.body.token); %}



###

POST http://localhost/kk-mgr/hello
Accept: */*
Cache-Control: no-cache
Content-Type: application/json;charset=utf-8
Authorization:  {{auth_token}}











