server:
  port: 80
  servlet:
    context-path: /kk-mgr
spring:
  profiles:
    active: sit
  jpa:
    open-in-view: true
    show-sql: false
    properties:
      entity-scan-packages: kim.kin
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
#        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    type: com.mysql.cj.jdbc.MysqlXADataSource
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: DatebookHikariCP
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      location: ${user.home}/multipartUpload
      max-file-size: 10MB
      max-request-size: 100MB
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false
    servlet:
      content-type: text/html

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
kim:
  kin:
    channel-no: '000'
    file-path: /data/file

jbpm:
  executor:
    enabled: false
  default:
    processId: com.sample.bpmn.hello
  bpmn2file:
    path: test.bpmn,hello.bpmn


