server:
  port: 80
  servlet:
    context-path: /kk-mgr
spring:
  profiles:
    active: sit
  datasource:
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: DatebookHikariCP
    type: com.zaxxer.hikari.HikariDataSource
  jackson:
    serialization:
      write-dates-as-timestamps: false
  servlet:
    multipart:
      location: ${user.home}/multipartUpload
      max-file-size: 10MB
      max-request-size: 100MB
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML
    cache: false
management:
  server:
    port: 15000
  #    servlet:
  #      context-path: /actuator
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
#  endpoints:
#    jmx:
#      exposure:
#        include: '*'
#    web:
#      base-path: /actuator
#      exposure:
#        include: '/actuator/*'
kim:
  kin:
    channel-no: '000'
    file-path: /data/file

